# Generated by Django 5.2.16 on 2026-07-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(blank=True, choices=[('LIGHT', 'Light'), ('DARK', 'Dark')], default='', max_length=8),
        ),
    ]
