# Generated by Django 5.2.15 on 2026-07-06 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('bucket', models.CharField(choices=[('PHYSICAL', 'Physical'), ('PENDING', 'Pending'), ('IN_TRANSIT', 'In transit')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('value_aed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='masterdata.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='products.product')),
            ],
            options={
                'ordering': ['product_id', 'location_id', 'bucket'],
                'indexes': [models.Index(fields=['location', 'bucket'], name='inventory_s_locatio_a3095b_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'location', 'bucket'), name='uniq_stock_balance')],
            },
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('txn_at', models.DateTimeField(db_index=True)),
                ('txn_type', models.CharField(choices=[('PURCHASE_ENTRY', 'Purchase line entered'), ('PURCHASE_COLLECTION', 'Purchase collection'), ('PURCHASE_REFUND', 'Purchase refund/cancellation'), ('SHIPMENT_OUT', 'Shipment shipped'), ('SHIPMENT_RECEIPT', 'Shipment receipt'), ('SHIPMENT_CANCEL', 'Shipment cancelled'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Stock adjustment'), ('EDIT_REVERSAL', 'Edit reversal'), ('DELETE_REVERSAL', 'Delete reversal')], max_length=32)),
                ('source_module', models.CharField(max_length=64)),
                ('source_id', models.BigIntegerField()),
                ('source_line_id', models.BigIntegerField(blank=True, null=True)),
                ('bucket', models.CharField(choices=[('PHYSICAL', 'Physical'), ('PENDING', 'Pending'), ('IN_TRANSIT', 'In transit')], max_length=16)),
                ('qty_in', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('qty_out', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('aed_value', models.DecimalField(decimal_places=2, default=0, help_text='AED value magnitude moved with this row; qty_in adds it, qty_out removes it.', max_digits=14)),
                ('gst_value', models.DecimalField(decimal_places=2, default=0, help_text='GST magnitude in AED where relevant; same direction convention as aed_value.', max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='masterdata.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='products.product')),
                ('related_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.location')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='inventory.stockledgerentry')),
            ],
            options={
                'verbose_name_plural': 'stock ledger entries',
                'ordering': ['-txn_at', '-id'],
                'indexes': [models.Index(fields=['product', 'location', 'bucket'], name='inventory_s_product_0d2132_idx'), models.Index(fields=['source_module', 'source_id'], name='inventory_s_source__a6e656_idx'), models.Index(fields=['txn_type', 'txn_at'], name='inventory_s_txn_typ_6d9ee2_idx')],
            },
        ),
    ]
