# Generated by Django 5.2.16 on 2026-07-15 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('masterdata', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('adjustment_date', models.DateField(db_index=True)),
                ('adjustment_type', models.CharField(choices=[('INCREASE', 'Increase (extra stock found, count correction up)'), ('DECREASE', 'Decrease (damaged, lost, count correction down)')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='masterdata.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-adjustment_date', '-id'],
                'indexes': [models.Index(fields=['location', 'adjustment_date'], name='inventory_s_locatio_57ba8e_idx')],
            },
        ),
    ]
