# Generated by Django 5.2.15 on 2026-07-06 16:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('refund_no', models.CharField(blank=True, db_index=True, max_length=64)),
                ('refund_date', models.DateField()),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='purchases.purchase')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-refund_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRefundLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(choices=[('PENDING', 'Pending (cancel undelivered)'), ('RECEIVED', 'Received (return delivered stock)')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('value_reversal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="In the line's currency.", max_digits=14)),
                ('value_reversal_aed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gst_reversal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="In the line's currency.", max_digits=14)),
                ('gst_reversal_aed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('location', models.ForeignKey(help_text='For RECEIVED refunds: where the returned stock leaves physical stock.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.location')),
                ('purchase_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_lines', to='purchases.purchaseline')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='purchases.purchaserefund')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
