# Generated by Django 5.2.15 on 2026-07-04 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login failed')], max_length=16)),
                ('module', models.CharField(blank=True, max_length=64)),
                ('record_id', models.BigIntegerField(blank=True, null=True)),
                ('record_repr', models.CharField(blank=True, max_length=255)),
                ('before_values', models.JSONField(blank=True, null=True)),
                ('after_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['module', 'record_id'], name='audits_audi_module_3bd207_idx'), models.Index(fields=['user', 'created_at'], name='audits_audi_user_id_254274_idx'), models.Index(fields=['action', 'created_at'], name='audits_audi_action_0f6a8b_idx')],
            },
        ),
    ]
